name: Get Semantic Version 
description: Github Action to get next semantic version based on latest tag and version bump info
author: uwblueprint
inputs:
  bump:
    description: The type of semantic version increment to make (one of major, premajor, minor, preminor, patch, prepatch, or prerelease)
    required: true
  token:
    description: GitHub token for GitHub API requests. Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
outputs:
  version:
    description: Incremented semantic version
runs:
  using: node16
  main: dist/index.js
